# ------ root_path/dataset_name ------
root_path: 'data'

seed: 3407

# ------ Hyperparamters ------
search_hp: True

search_scale: [7, 7, 1]
search_step: [200, 20, 20]

init_beta: 1
init_alpha: 3
init_gamma: 0.1

eps: 0.001
training_feat_num: 512
training_free_feat_num: 512

w_training_free: [0.4, 0.6]
w_training: [0.2, 0.8]

# ------ Basic Config ------
dataset: 'oxford_flowers'
backbone: 'RN50'

lr: 0.001
augment_epoch: 10
train_epoch: 60


## ------ root_path/dataset_name ------
#root_path: './data'
#seed: 1
#
## ------ Load Cache and Features ------
#load_cache: False
#load_pre_feat: False
#
load_cache: True
load_pre_feat: True
#
#
## ------ Hyperparamters ------
#search_hp: True
##search_hp: False
#
#search_scale: [50, 50]
#search_step: [200, 20]
#
#init_beta: 1
#init_alpha: 10
#
#
## ------ Basic Config ------
#dataset: 'oxford_flowers'
shots: 16
#backbone: 'RN50'
#
## ------ Data Split ------
data_section: 0
#
#lr: 0.001
#augment_epoch: 10
#train_epoch: 20
