# ------ root_path/dataset_name ------
root_path: './data'

# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False
#load_cache: True
#load_pre_feat: True


# ------ Basic Config ------
dataset: 'Places'
backbone: 'RN50'