# ------ root_path/dataset_name ------
root_path: '/home/nfs03/zengtc'
seed: 3407

# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False
#load_cache: True
#load_pre_feat: True


# ------ Basic Config ------
dataset: 'SUN'
backbone: 'ViT-B/16'